### ISSUE TITLE
Msys2 can't find libgl@

### ISSUE THREAD

**Issue by Juliallisio** [FluffyStuff/OpenRiichi#26]
`julia@DESKTOP-6FNMMLT MINGW64 ~/OpenRiichi
$ ninja -C build
ninja: Entering directory `build'
[1/1] Linking target OpenRiichi.exe
FAILED: OpenRiichi.exe
cc @OpenRiichi.exe.rsp
cc: error: libgl@: No such file or directory
ninja: build stopped: subcommand failed.
`

**Comment by FluffyStuff** [comment]
Could you try downloading and installing the [Windows SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/) and see if this resolves the issue?

**Comment by Juliallisio** [comment]
(Sorry about the late reply)


> 
> 
> Could you try downloading and installing the [Windows SDK](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/) and see if this resolves the issue?

No, same issue. 

I managed to build the program using the ubuntu terminal in windows store and following the linux steps using another copy of the repository. But now it's giving me this error when I try to run it

> [2020-05-03_11-39-33] INFO from Environment(01): Logging started (0.2.1.0)

> error: XDG_RUNTIME_DIR not set in the environment.

> [2020-05-03_11-39-33] SYSTEM from SDLGLEngine(01): Could not init SDL

> [2020-05-03_11-39-33] ERROR from Main(01): Could not init engine

After that I ran

> /mnt/c/OpenRiichi$ export XDG_RUNTIME_DIR=/mnt/c/OpenRiichi/bin/ 
(In the readme says that it should be /usr/share/OpenRiichi, but that folder was not created)
After that I get the same message without the error:XDG_RUNTIME... line

**Comment by FluffyStuff** [comment]
You need to run the executable with the argument `--search-directory /mnt/c/OpenRiichi/bin/`

But I also pushed a new commit which might resolve your issue for the mingw build. Could you give that a try?

**Comment by Juliallisio** [comment]
I'm still having the same problem in mingw.
In the ubuntu terminal using the --search-directory option gave me the same error, so I re-installed the game again using meson build -Dbuildtype=debug and it gives me this error 
> [2020-05-04_11-55-17] DEBUG from FileLoader.load(01): File does not exist: /home/julian/.config/OpenRiichi/options.cfg
And the file is not there
> julian@DESKTOP-6FNMMLT:~/.config/OpenRiichi$ ls
> logs
Is there any way to get that options file so I can copy/paste it there?

**Comment by FluffyStuff** [comment]
It's just a debug message. The file will get auto generated once the application starts successfully.
Just as a sanity check, are you able to run a [prebuilt binary](https://github.com/FluffyStuff/OpenRiichi/releases/tag/v0.2.1.1)?

**Comment by band-a-prend** [comment]
I tried to build OpenRiichi on Gentoo Linux (tying to package it or build locally) and it failed to start with errors
```
$ OpenRiichi 
[2020-10-04_22-39-13] INFO from Environment(01): Logging started (0.2.1.1)
[2020-10-04_22-39-13] SYSTEM from SDLGLEngine(01): Could not init SDL
[2020-10-04_22-39-13] ERROR from Main(01): Could not init engine
```
If packaging then the files installed into
```
/usr/bin/OpenRiichi (*executable)
/usr/share/OpenRiichi/Data/Audio/Music/*.ogg
/usr/share/OpenRiichi/Data/Audio/Sounds/*.wav
/usr/share/OpenRiichi/Data/Fonts/*.otf
/usr/share/OpenRiichi/Data/Icon.png
/usr/share/OpenRiichi/Data/Models/{*.mlt,*obj}
/usr/share/OpenRiichi/Data/Textures/Buttons/*.png
/usr/share/OpenRiichi/Data/Textures/Menu/*.png
/usr/share/OpenRiichi/Data/Textures/Sticks/*.png
/usr/share/OpenRiichi/Data/Textures/Tiles/Black/*.png
/usr/share/OpenRiichi/Data/Textures/Tiles/Regular/*.png
/usr/share/OpenRiichi/Data/Textures/WindIndicators/*.png
/usr/share/OpenRiichi/Data/Textures/*.png
/usr/share/doc/openriichi-0.2.1.1/README.md.bz2
```
The OpenRiichi is built against
```
dev-lang/vala-0.48.9
sys-devel/gcc-9.3.0
dev-util/meson-0.54.3
dev-libs/libgee-0.20.3:0.8
media-libs/glew-2.2.0
x11-libs/pango-1.42.4
media-libs/libsdl2-2.0.12
media-libs/sdl2-image-2.0.4
media-libs/sdl2-mixer-2.0.4
x11-libs/gtk+-3.24.22
```

If any any additional information is required?
Is it require pulseaudio to run? I use alsa in my system.

**Comment by band-a-prend** [comment]
As I got a tip on one of [russian Linux community forum](https://www.linux.org.ru/forum/games/15979593?cid=15979870) on the base of [Engine/blob/master/vapi/sdl2.vapi](https://github.com/FluffyStuff/Engine/blob/e495846970a1b38d00c81a3f74568030f976ed31/vapi/sdl2.vapi#L33-L36)
```
	public enum InitFlag {
		TIMER, AUDIO, VIDEO, JOYSTICK, HAPTIC,
		GAMECONTROLLER, NOPARACHUTE, EVERYTHING
	}// InitFlag
```
I have to build libsdl2 additionally with the `haptic (force feedback) subsystem ` support.

So currently I successfully able to run and play game built against following Gentoo packages  
(+ on the base of [Engine/blob/vapi/SDL2_image.vapi](https://github.com/FluffyStuff/Engine/blob/e495846970a1b38d00c81a3f74568030f976ed31/vapi/SDL2_image.vapi#L35-L42)):
```
dev-libs/glib-2.64.5
dev-libs/gobject-introspection-1.64.1-r1
dev-libs/libgee-0.20.3:0.8
media-libs/glew-2.2.0:0
media-libs/libsdl2-2.0.12-r2[haptic,joystick,opengl,sound,threads,video]
media-libs/sdl2-image-2.0.5[jpeg,png,tiff,webp] 
media-libs/sdl2-mixer-2.0.4
x11-libs/gtk+-3.24.22:3
x11-libs/pango-1.42.4-r2
```
